
services:
  db:
    image: postgres:latest
    container_name: mobiauto_db
    restart: always
    environment:
      POSTGRES_USER: mobiauto
      POSTGRES_PASSWORD: VCqOSDUQ0K30JxDAJ
      POSTGRES_DB: mobiauto
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
